project_id: '585007'
api_token: '8409fee9283302be9e3a10545bdbce8567c1be42d4dea9ef759ce3f16847fe6801c5112d38d2ba69'
files:
  # JSON translation files
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
    languages_mapping:
      two_letters_code:
        en: en
        es-ES: es_ES
  # Docs Markdown files
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    languages_mapping:
      two_letters_code:
        en: en
        es-ES: es_ES
