project_id_env: 'CROWDIN_PROJECT_ID'
api_token_env: 'CROWDIN_PERSONAL_TOKEN'
base_path: '.'
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true

files:
  # JSON translation files
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
    languages_mapping:
      two_letters_code:
        en: en
        es-ES: es_ES
        fr-FR: fr_FR
  # Docs Markdown files
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    languages_mapping:
      two_letters_code:
        en: en
        es-ES: es_ES
        fr-FR: fr_FR
