/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  // tutorialSidebar1: [
  //   'intro',
  //   {
  //     type: 'autogenerated',
  //     dirName: 'core-concepts',
  //   },
  //   {
  //     type: 'autogenerated',
  //     dirName: 'languages',
  //   },
  // ],

  // tutorialSidebar2: [
  //     'intro',
  //     {'core-concepts': ['api-calls-anatomy','websocket']},
  //     {'guides':['getting-to-know-the-api','markup-calculation','oauth2','ways-to-monetize-deriv-api'] }
  //   ],
};

module.exports = sidebars;
