name: npm_install_from_cache
description: Install npm packages from cache
runs:
  using: composite
  steps:
    - name: Cache node modules
      id: cache-nodemodules
      uses: actions/cache/restore@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install npm dependencies
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: npm install
      shell: bash
