name: Coveralls Workflow
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Setup Node
        uses: './.github/actions/setup_node'
      - name: Install dependencies
        uses: './.github/actions/npm_install_from_cache'
      - name: Build
        uses: ./.github/actions/test_build
      - name: Run Tests
        run: npm run test  -- --collectCoverage
      - name: Coveralls
        uses: coverallsapp/github-action@3dfc5567390f6fa9267c0ee9c251e4c8c3f18949
